### ISSUE TITLE
Would you like to share the training data?

### ISSUE THREAD

**Issue by created-Bi** [shunk031/simple-aesthetics-predictor#17]
I'm wondering what the training data you use? Thanks~

**Comment by shunk031** [comment]
Hi @created-Bi, thank you for your interest in this repository.

This library is a wrapper that provides the transformers API of aesthetic predictor published below:
- LAION-AI/aesthetic-predictor: A linear estimator on top of clip to predict the aesthetic quality of pictures https://github.com/LAION-AI/aesthetic-predictor 
- christophschuhmann/improved-aesthetic-predictor: CLIP+MLP Aesthetic Score Predictor https://github.com/christophschuhmann/improved-aesthetic-predictor 

Sorry for the confusion, and I will update the README in #18 with this information.
